resources:
  requests:
    cpu: 50m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
  java_opts:
    - "-server -Xms512M -Xmx1G"
    - "-XX:+UseContainerSupport"
    - "-XX:+AlwaysActAsServerClassMachine"