resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi
  java_opts:
    - "-server -Xms512M -Xmx512M"
    - "-XX:MaxRAMPercentage=85.0"
    - "-XX:+UseContainerSupport"
    - "-XX:+AlwaysActAsServerClassMachine"