namespace: default

deployment:
  replicas: 1
  restart_policy: Always
  image_pull_policy: Never

  health:
    progress_deadline_seconds: 90
    initial_delay_seconds: 40
    period_seconds: 10
    timeout_seconds: 5
    failure_threshold: 5