resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
  java_opts:
    - "-server -Xms128M -Xmx256M"
    - "-XX:MaxRAMPercentage=85.0"
    - "-XX:+UseContainerSupport"
    - "-XX:+AlwaysActAsServerClassMachine"