name: "release"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          architecture: x64
          java-version: 11

      - name: Gradle Test
        run: ./gradlew build

      - name: Tag Bump and Push
        id: bump
        uses: anothrNick/github-tag-action@1.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: master

      - name: Docker Build and Push
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: illine/gateway
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ steps.bump.outputs.new_tag }}"

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Image Tag
        run: echo ::set-env name=IMAGE_TAG::$(echo ${{needs.build.outputs.new_tag}})
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Setup Kubernetes Config Directory
        run: echo ::set-env name=K8S_DIR::$(echo ".ansible/configs/k8s")
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Generate Configs by Ansible Playbook
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: .ansible/main.yaml
          inventoryFile: .ansible/inventories/prod/hosts.yml
          extraVars: -e env=prod

      - name: Upload Kubernetes ConfigMap
        uses: ameydev/gke-kubectl-action@v1.02
        env:
          PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_AUTH }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: ${{ secrets.GKE_ZONE_NAME }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          args: apply -f $K8S_DIR/config-map.yaml

      - name: Upload Kubernetes Service
        uses: ameydev/gke-kubectl-action@v1.02
        env:
          PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_AUTH }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: ${{ secrets.GKE_ZONE_NAME }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          args: apply -f $K8S_DIR/service.yaml

      - name: Upload Kubernetes Deployment
        uses: ameydev/gke-kubectl-action@v1.02
        env:
          PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_AUTH }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: ${{ secrets.GKE_ZONE_NAME }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          args: apply -f $K8S_DIR/deployment.yaml --record